### ISSUE TITLE
[doc] Procedure&nbsp;2.9:  Pull Data From Upstream Sources 

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#135] opened 2019-02-05 14:00 UTC
Procedure&nbsp;2.9:  Pull Data From Upstream Sources 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#id-1.4.4.3.12.4

--------------

When I follow these instructions I get this output of helm-mirror:

helm-mirror inspect-images /srv/www/htdocs/kubernetes-charts.suse.com/ -o skopeo=x.yaml
helm-mirror: 2019/02/05 14:57:55.037049 inspectImages.go:136: error: cannot render chart: render error in "cf/templates/tcp-router.yaml": template: cf/templates/tcp-router.yaml:42:28: executing "cf/templates/tcp-router.yaml" at <include (print $.Tem...>: error calling include: template: cf/templates/secrets.yaml:5:29: executing "cf/templates/secrets.yaml" at <required "secrets.CL...>: error calling required: secrets.CLUSTER_ADMIN_PASSWORD has not been set
helm-mirror: 2019/02/05 14:57:55.037206 inspectImages.go:93: error: cannot load chart: render error in "cf/templates/tcp-router.yaml": template: cf/templates/tcp-router.yaml:42:28: executing "cf/templates/tcp-router.yaml" at <include (print $.Tem...>: error calling include: template: cf/templates/secrets.yaml:5:29: executing "cf/templates/secrets.yaml" at <required "secrets.CL...>: error calling required: secrets.CLUSTER_ADMIN_PASSWORD has not been set
helm-mirror: 2019/02/05 14:57:55.037251 inspectImages.go:100: error walking the path "/srv/www/htdocs/kubernetes-charts.suse.com/": render error in "cf/templates/tcp-router.yaml": template: cf/templates/tcp-router.yaml:42:28: executing "cf/templates/tcp-router.yaml" at <include (print $.Tem...>: error calling include: template: cf/templates/secrets.yaml:5:29: executing "cf/templates/secrets.yaml" at <required "secrets.CL...>: error calling required: secrets.CLUSTER_ADMIN_PASSWORD has not been set
helm-mirror: 2019/02/05 14:57:55.037285 inspectImages.go:62: error: procesing target /srv/www/htdocs/kubernetes-charts.suse.com/: render error in "cf/templates/tcp-router.yaml": template: cf/templates/tcp-router.yaml:42:28: executing "cf/templates/tcp-router.yaml" at <include (print $.Tem...>: error calling include: template: cf/templates/secrets.yaml:5:29: executing "cf/templates/secrets.yaml" at <required "secrets.CL...>: error calling required: secrets.CLUSTER_ADMIN_PASSWORD has not been set
Error: render error in "cf/templates/tcp-router.yaml": template: cf/templates/tcp-router.yaml:42:28: executing "cf/templates/tcp-router.yaml" at <include (print $.Tem...>: error calling include: template: cf/templates/secrets.yaml:5:29: executing "cf/templates/secrets.yaml" at <required "secrets.CL...>: error calling required: secrets.CLUSTER_ADMIN_PASSWORD has not been set
Usage:
  mirror inspect-images [folder|tgzfile] [flags]

Flags:
  -h, --help            help for inspect-images
  -o, --output string   choose an output for the list of images and specify
                        the file name, if not specified 'images.out' will be the default.
                        Options:

                        - file: outputs all images to a file
                        - json: outputs all images to a file in JSON format
                        - skopeo: outputs all images to a file in YAML format
                          to be used as source file with the 'skopeo sync' command.
                          For more information refer to the 'skopeo sync'
                          documentation at https://github.com/SUSE/skopeo/blob/sync/docs/skopeo.1.md#skopeo-sync
                        - stdout: prints all images to standard output
                        - yaml: outputs all images to a file in YAML format

                        Usage:

                                - helm mirror inspect-images /tmp/helm --output stdout
                                - helm mirror inspect-images /tmp/helm -o stdout
                                - helm mirror inspect-images /tmp/helm -o file=filename
                                - helm mirror inspect-images /tmp/helm -o json=filename.json
                                - helm mirror inspect-images /tmp/helm -o yaml=filename.yaml
                                - helm mirror inspect-images /tmp/helm -o skopeo=filename.yaml

                         (default "stdout")

Global Flags:
  -i, --ignore-errors   ignores errors while downloading or processing charts
  -v, --verbose         verbose output

render error in "cf/templates/tcp-router.yaml": template: cf/templates/tcp-router.yaml:42:28: executing "cf/templates/tcp-router.yaml" at <include (print $.Tem...>: error calling include: template: cf/templates/secrets.yaml:5:29: executing "cf/templates/secrets.yaml" at <required "secrets.CL...>: error calling required: secrets.CLUSTER_ADMIN_PASSWORD has not been set

**Comment by r0ckarong** [comment] 2019-02-05 14:33
Please run the command again with the `--ignore-errors` parameter. 

This is a known problem of some of the CAP related charts: https://bugzilla.suse.com/show_bug.cgi?id=1116570

**Comment by Martin-Weiss** [comment] 2019-02-06 14:52
> 
> 
> Please run the command again with the `--ignore-errors` parameter.
> 
> This is a known problem of some of the CAP related charts: https://bugzilla.suse.com/show_bug.cgi?id=1116570

I had a look at this bug and I believe this is not a bug in the CAP related charts it is a bug in the helm-mirror tool.

I get the same problem with a mirror of kubernetes-charts.storage.googleapis.com:

helm-mirror inspect-images /srv/www/htdocs/kubernetes-charts.storage.googleapis.com/ -o skopeo=/srv/www/htdocs/kubernetes-charts.storage.googleapis.com/skopeo.yaml

-> shows many many erros.

Could we at least add the "--ignore-errors" to the documentation until we have a fix for helm-mirror?

**Comment by r0ckarong** [comment] 2019-02-06 16:38
It's not a bug in the helm-mirror tool. The CAP charts and those Google charts have values that are filled from the environment on respective chart repos. We can never know these.

For this reason the mirroring of charts from sources other than SUSE is not supported. The CAP charts will be fixed in time but we can not do anything about how other repositories handle their charts.

Please also see the response here: https://bugzilla.suse.com/show_bug.cgi?id=1124335#c2

I will amend the documentation to explain how and why to use `--ignore-errors`.

**Comment by Martin-Weiss** [comment] 2019-02-06 17:28
> Am 06.02.2019 um 17:39 schrieb Markus Napp <notifications@github.com>:
> 
> It's not a bug in the helm-mirror tool.
> 

Then the tool might not be fulfilling requirements.

> The CAP charts and those Google charts have values that are filled from the environment on respective chart repos. We
can never know these.
> 
We need the images and these are known - can be found in the values.yaml.
What else do we need to know?

> For this reason the mirroring of charts from sources other than SUSE is not supported.
> 
And what about all other Helm repos? Do we have to clone them manually? If yes - then the helm-mirror tool might not be
very useful at all..
(Most applications are not in the SUSE Helm repo)

> The CAP charts will be fixed in time but we can not do anything about how other repositories handle their charts.
> 
Not sure if this is true - where can I find the RFC for valid Helm charts?

> Please also see the response here: https://bugzilla.suse.com/show_bug.cgi?id=1124335#c2
> 
Will check this tomorrow.
> I will amend the documentation to explain how and why to use --ignore-errors.
> 
Thanks!

**Comment by r0ckarong** [comment] 2019-02-08 10:59
Note about `--ignore-errors` flag added with https://github.com/SUSE/doc-caasp/commit/ed55505f3417548ad8c9926f11167b932f411fa0

Please move the discussion about featureset and requirements for helm-mirror to this bugzilla thread.

**Closed by r0ckarong** 2019-02-08 10:59 UTC
Labels: Bug, v3, v4
