### ISSUE TITLE
[doc] 5.2.1  How To Update Nodes

### ISSUE THREAD

**Issue by savasirez** [SUSE/doc-caasp#667] opened 2020-01-15 21:57 UTC
Below section only works if you upgrade the addons first. So, I think a new section or an explanation is needed here to upgrade the addons first. Below is what happens if you try to upgrade:

`caas4master:~/caas4-demo # skuba cluster upgrade plan
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.16.2

Upgrade path to update from 1.15.2 to 1.16.2:
 - 1.15.2 -> 1.16.2

Addon upgrades for 1.16.2:
  - cilium: 1.5.3 (new addon)
  - dex: 2.16.0 (new addon)
  - gangway: 3.1.0-rev4 (new addon)
  - kured: 1.2.0-rev4 (new addon)
  - psp:  (new addon)

caas4master:~/caas4-demo # skuba node upgrade apply --target caas4master
W0115 15:09:33.007072   31491 ssh.go:309]
I0115 15:09:33.007121   31491 ssh.go:311] adding fingerprint for "caas4master:22" to "known_hosts"
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.16.2
Current Node version: 1.15.2

**Unable to apply node upgrade: node caas4master cannot be upgraded yet. The following errors were detected:
 - There are addon upgrades available for the current cluster version (1.15.2) that need to be applied first**

**caas4master:~/caas4-demo # skuba addon upgrade apply**
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.16.2

**[apply] Successfully upgraded addons**
**caas4master:~/caas4-demo # skuba addon upgrade plan**
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.16.2

**Congratulations! Addons for 1.15.2 are already at the latest version available**

caas4master:~/caas4-demo # skuba node upgrade apply --target caas4master
W0115 15:20:31.351997   10690 ssh.go:309]
I0115 15:20:31.352049   10690 ssh.go:310] accepting SSH key for "caas4master:22"
I0115 15:20:31.352061   10690 ssh.go:311] adding fingerprint for "caas4master:22" to "known_hosts"
Current Kubernetes cluster version: 1.15.2
Latest Kubernetes version: 1.16.2
Current Node version: 1.15.2

Fetching the cluster configuration...
Performing node caas4master (caas4master) upgrade, please wait...
E0115 15:20:38.143877   10690 ssh.go:193] Removed /etc/systemd/system/timers.target.wants/skuba-update.timer.
E0115 15:25:53.263240   10690 ssh.go:193] Created symlink /etc/systemd/system/timers.target.wants/skuba-update.timer → /usr/lib/systemd/system/skuba-update.timer.
Node caas4master (caas4master) successfully upgraded

caas4master:~/caas4-demo # skuba node upgrade apply --target caas4node1
W0115 15:35:20.722972   28839 ssh.go:309]
I0115 15:35:20.723039   28839 ssh.go:310] accepting SSH key for "caas4node1:22"
I0115 15:35:20.723049   28839 ssh.go:311] adding fingerprint for "caas4node1:22" to "known_hosts"
Current Kubernetes cluster version: 1.16.2
Latest Kubernetes version: 1.16.2
Current Node version: 1.15.2

Performing node caas4node1 (caas4node1) upgrade, please wait...
E0115 15:35:27.191960   28839 ssh.go:193] Removed /etc/systemd/system/timers.target.wants/skuba-update.timer.
E0115 15:37:02.546449   28839 ssh.go:193] Created symlink /etc/systemd/system/timers.target.wants/skuba-update.timer → /usr/lib/systemd/system/skuba-update.timer.
Node caas4node1 (caas4node1) successfully upgraded

^Ccaas4master:~/caas4-demo skuba node upgrade apply --target caas4node2
W0115 15:40:44.124241   32631 ssh.go:309]
I0115 15:40:44.124303   32631 ssh.go:310] accepting SSH key for "caas4node2:22"
I0115 15:40:44.124317   32631 ssh.go:311] adding fingerprint for "caas4node2:22" to "known_hosts"
Current Kubernetes cluster version: 1.16.2
Latest Kubernetes version: 1.16.2
Current Node version: 1.15.2

Performing node caas4node2 (caas4node2) upgrade, please wait...
E0115 15:40:50.632299   32631 ssh.go:193] Removed /etc/systemd/system/timers.target.wants/skuba-update.timer.
E0115 15:42:21.984443   32631 ssh.go:193] Created symlink /etc/systemd/system/timers.target.wants/skuba-update.timer → /usr/lib/systemd/system/skuba-update.timer.
Node caas4node2 (caas4node2) successfully upgraded

caas4master:~/caas4-demo # skuba node upgrade apply --target caas4node3
W0115 15:48:41.275622    5829 ssh.go:309]

I0115 15:48:41.275677    5829 ssh.go:310] accepting SSH key for "caas4node3:22"
I0115 15:48:41.275683    5829 ssh.go:311] adding fingerprint for "caas4node3:22" to "known_hosts"
Current Kubernetes cluster version: 1.16.2
Latest Kubernetes version: 1.16.2
Current Node version: 1.15.2

Performing node caas4node3 (caas4node3) upgrade, please wait...
E0115 15:48:47.734775    5829 ssh.go:193] Removed /etc/systemd/system/timers.target.wants/skuba-update.timer.
E0115 15:50:22.889539    5829 ssh.go:193] Created symlink /etc/systemd/system/timers.target.wants/skuba-update.timer → /usr/lib/systemd/system/skuba-update.timer.
Node caas4node3 (caas4node3) successfully upgraded

`

5.2.1  How To Update Nodes

https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_cluster_updates.html#_how_to_update_nodes

**Comment by r0ckarong** [comment] 2020-01-16 14:09
Possible duplicate of https://github.com/SUSE/doc-caasp/issues/664

**Closed** 2020-01-16 14:11 UTC
Labels: 4.1.1, AdminGuide, Reported, v4
