### ISSUE TITLE
[doc] 7.1.4.2  ETCD Cluster

### ISSUE THREAD

**Issue by mkiss-katacoda** [SUSE/doc-caasp#968] opened 2020-08-13 09:50 UTC
7.1.4.2  ETCD Cluster:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_etcd_cluster

extraScrapeConfigs: |
  - job_name: etcd
    static_configs:
    - targets: ['192.168.0.32:2379','192.168.0.17:2379','192.168.0.5:2379'

missing closing ]

**Comment by r0ckarong** [comment] 2020-08-13 10:16
Duplicate of #890, was missing backport to 4.2.x. Closed with 189d95d

**Closed by r0ckarong** 2020-08-13 10:16 UTC
Labels: Bug, duplicate
