### ISSUE TITLE
Sudo issue during "minimal" installation

### ISSUE THREAD

**Issue by rkoktan** [SUSE/doc-caasp#509] opened 2019-09-20 18:36 UTC
The docs suggest in section 3.3.2.1, step 6, to use the "minimal" System Role for master and worker node installations, however, if one does so, "sudo" does not get installed, and thus subsequent steps fail as a result, for example, section 4.2 "echo "USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers" fails on account that the sudoers file does not exist without sudo installed.  Farther along, during bootstrapping in section 4.2.5, all commands with "--sudo" in them will fail as well...
skuba node bootstrap --user sles --sudo --target <IP/FQDN> <NODE NAME>

Installing sudo with "# zypper in sudo" after initial installation of nodes solves all of these.

**Comment by r0ckarong** [comment] 2019-09-23 10:13
This is a duplicate of #491 

3.3.2.2 describes how additional packages (including sudo) must be installed.

**Closed by r0ckarong** 2019-09-23 10:13 UTC

**Comment by rkoktan** [comment] 2019-09-23 18:41
I see that now that you've pointed it out, however, based on the section title, "Preparation of the VM as a Template", I skipped this section as I was installing on KVM VMs, not VMware templates, so perhaps this info could be re-iterated in the Bare Metal section?

**Comment by r0ckarong** [comment] 2019-09-24 10:38
@rkoktan So you installed KVM on baremetal without AutoYaST? Or does AY select the minimal sles image?

**Comment by rkoktan** [comment] 2019-09-24 12:53
I'd be happy to help, but am not sure if KVM makes use of "templates" as VMware does, will have to look in to it...
Yes, that's exactly what I meant by pulling from different sections , I read thru all the sections and noticed differences and had to make use of content from multiple sections to get my KVM lab to work.

**Comment by rkoktan** [comment] 2019-09-24 12:53
Haha, well neither is XEN a supported platform, but customers use it in produciton nonetheless!
