### ISSUE TITLE
[doc] 5  Upgrading SUSE CaaS Platform - need an overview helm chart versions <-> CaaSP version that are supported

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#994] opened 2020-09-16 10:00 UTC
5  Upgrading SUSE CaaS Platform:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_upgrading_suse_caas_platform

----------------------
We are upgrading 4.2.1 to 4.2.3 and later to 4.5.
Now during the upgrade from 4.2.1 to 4.2.3 we find many helm charts on kubernetes-charts.suse.com that use images from 4.5 - so we do NOT know which helm chart / which application we have to update BEFORE we go to 4.5 and which ones AFTER and we do not know which helm chart version running in the cluster is valid for which CaaSP version..

So can we add an overview that shows that?

In addition to that we need a "txt" similar like https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt for all the images required by the helm charts we provide. Could we also get that?

**Comment by r0ckarong** [comment] 2020-09-16 11:53
This is basically a duplicate of the unresolved portion of #621 

@jordimassaguerpla How could we provide that in a maintainable way?

**Comment by r0ckarong** [comment] 2020-10-22 10:15
This is a duplicate of pending #775

**Closed by r0ckarong** 2020-10-22 10:15 UTC
Labels: AdminGuide, Blocked, EngineeringInput
