### ISSUE TITLE
[doc] 9.1.1.2.2.2  Minio

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#789] opened 2020-04-30 11:41 UTC
9.1.1.2.2.2  Minio

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_minio

You must also define a region name or else velero can't connect to minio
export MINIO_REGION_NAME=<region_name>

**Comment by r0ckarong** [comment] 2020-05-04 09:14
@innobead Could you give me the correct example how to do this and verify please? Thanks

**Comment by innobead** [comment] 2020-05-04 13:24
@jenting please help with this. Thanks.

**Comment by jenting** [comment] 2020-05-05 01:22
@tgeek77 
Sorry, I can't reproduce it.

What's the _region-name_ setting `--set configuration.backupStorageLocation.config.region` when helm install?
Is your minio server in _or_ out k8s cluster?

**Comment by tgeek77** [comment] 2020-05-05 13:19
I can't reproduce it again either.

**Comment by jenting** [comment] 2020-05-05 13:32
Never mind~
Closing the issue, feel free to re-open if you find the way to reproduce it, thanks :bow:

**Closed by jenting** 2020-05-05 13:32 UTC
Labels: 4.2.1, AdminGuide
