### ISSUE TITLE
Changing Velum Admin Password 

### ISSUE THREAD

**Issue by otuominen** [SUSE/doc-caasp#112] opened 2018-12-03 13:29 UTC
Procedure&nbsp;1.2:  Changing Velum Admin Password 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#id5412

# docker exec -it $(docker ps -q -f name=ldap) /bin/bash

```
bash-4.3# slappasswd -n -s password
{SSHA}SSK3rBatmgUNrDmohlOw5JMhVB/vvEcG

bash-4.3# ldappasswd -H ldaps:// -D "cn=admin,dc=infra,dc=caasp,dc=local" \
-w $(cat /var/lib/misc/infra-secrets/openldap-password) \
uid=test,ou=People,dc=infra,dc=caasp,dc=local -s {SSHA}SSK3rBatmgUNrDmohlOw5JMhVB/vvEcG
Result: No such object (32)
```

**Comment by r0ckarong** [comment] 2018-12-03 13:40
Did you put in the hostname of your LDAP instance in place of `ldaps://`?

**Comment by r0ckarong** [comment] 2018-12-03 14:07
There seems to be a problem finding the admin user in the database with the attributes. I'm looking into this.

**Comment by otuominen** [comment] 2018-12-03 16:37
> There seems to be a problem finding the admin user in the database with the attributes. I'm looking into this.

**Comment by otuominen** [comment] 2018-12-03 16:42
Reopening.

**Comment by nanoscopic** [comment] 2018-12-03 23:20
Assuming that there exists a cn=admin user in the LDAP DB, the following command would output the full DN of that user:
( executed from LDAP container context )
`slapcat -n1 | grep "dn: cn=admin"`

If nothing appears one could browse through the `slapcat -n1` output to see everything that is there.

If there is no user present then something has gone wrong. When a cluster is first created the cn=admin user is created by Velum; so it should always be there.

My guess without interacting with the specific cluster having the problem is that the domain for the cn=admin user is different. The default domain context is "infra.caasp.local". It is possible for that domain to be configured differently for a user.

**Comment by r0ckarong** [comment] 2018-12-04 10:17
@otuominen Try this:
Follow the instructions until you are in the bash of the LDAP container.
Then run: `slapcat -n1 | grep uniqueMember`
`uniqueMember: uid=mnapp,ou=People,dc=infra,dc=caasp,dc=local` <- this line will look different for you.

Then replace the `uid` in the password change command with the uid from the output. 

So replace `uid=test` here with the uid from your output: 

```
bash-4.3# ldappasswd -H ldaps:// -D "cn=admin,dc=infra,dc=caasp,dc=local" -w $(cat /var/lib/misc/infra-secrets/openldap-password) uid=test,ou=People,dc=infra,dc=caasp,dc=local -S
```

If any of the other attributes are different, change them too (should not be the case).

**Comment by otuominen** [comment] 2018-12-04 12:19
> @otuominen Try this:
> Follow the instructions until you are in the bash of the LDAP container.
> Then run: `slapcat -n1 | grep uniqueMember`
> `uniqueMember: uid=mnapp,ou=People,dc=infra,dc=caasp,dc=local` <- this line will look different for you.
> 
> Then replace the `uid` in the password change command with the uid from the output.
> 
> So replace `uid=test` here with the uid from your output:
> 
> ```
> bash-4.3# ldappasswd -H ldaps:// -D "cn=admin,dc=infra,dc=caasp,dc=local" -w $(cat /var/lib/misc/infra-secrets/openldap-password) uid=test,ou=People,dc=infra,dc=caasp,dc=local -S
> ```
> If any of the other attributes are different, change them too (should not be the case).

So yes, slapcat -n1 | grep uniqueMember` is essential that you capture correct uid!

bash-4.3# slapcat -n1 | grep uniqueMember
5c067044 mdb_monitor_db_open: monitoring disabled; configure monitor database to enable
uniqueMember: uid=admin,ou=People,dc=infra,dc=caasp,dc=local
bash-4.3# ldappasswd -H ldaps:// -D "cn=admin,dc=infra,dc=caasp,dc=local" -w $(cat /var/lib/misc/infra-secrets/openldap-password) uid=admin,ou=People,dc=infra,dc=caasp,dc=local -S
New password: 
Re-enter new password:

That should be included as info. Thanks!

**Comment by r0ckarong** [comment] 2018-12-04 12:22
I have already changed the instructions to extract this information and this will be updated with a future update of the docs. I'll close this issue.

**Closed by r0ckarong** 2018-12-04 12:22 UTC
Labels: Bug
