### ISSUE TITLE
[doc] 6.9.2  Certificate Validity - 1 or 2 years?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1013] opened 2020-09-25 07:51 UTC
6.9.2  Certificate Validity:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_certificate_validity

--------------------
> Client and server certificates are valid for 365 days (1 year) by default.

I just had to realize that in my cluster the etcd-client-certificate in cilium-secret has a 2 year lifetime but at the customer I have seen 1 year.. are we sure that the 1 year is correct for all versions, certificates and deployments?

**Comment by r0ckarong** [comment] 2020-09-25 09:08
@jenting

**Comment by jenting** [comment] 2020-09-28 01:49
@Martin-Weiss ,
I check the skuba code, from the first release version 4.0 to now, the certificate is generated by using _kubeadm_ library
- https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L83
- https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L568
- https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L49

Perhaps your cilium etcd client certificate had ever be renewed?

**Comment by Martin-Weiss** [comment] 2020-09-29 09:37
I have no idea - but at the customer the certificate in admin.conf AND in cilium-secret both had 1 year lifetime and not 2..

**Comment by jenting** [comment] 2020-09-30 01:08
@mrostecki when we upgrade the cilium version from 1.5->1.6 or 1.6->1.7, will cilium itself do certificate extension?
@Martin-Weiss could you please get the cilium version of your K8s cluster and customer K8s cluster?

**Comment by Martin-Weiss** [comment] 2020-09-30 09:26
Who is creating and updating the clium-secret? Isn´t skuba doing that?
At the customer we have cilium 1.5.3 and in my cluster I have 1.7.5 - but my secret has these dates:
notBefore=Sep 17 09:23:49 2019 GMT
notAfter=Sep 15 09:14:20 2021 GMT
At the customer we have seen notBefore 2019 and notAfter 2020..

**Comment by jenting** [comment] 2020-10-05 03:24
> Who is creating and updating the clium-secret? Isn´t skuba doing that?

I believe yes, but I've to check each skuba release whether the skuba will extend the client certificate.
But if I remember correctly, the cilium client certificate generates if the Secret `cilium-secret` not exist when cluster bootstrap or upgrade.

> At the customer we have cilium 1.5.3 and in my cluster I have 1.7.5 - but my secret has these dates:
> notBefore=Sep 17 09:23:49 2019 GMT
> notAfter=Sep 15 09:14:20 2021 GMT
> At the customer we have seen notBefore 2019 and notAfter 2020..

**Comment by jenting** [comment] 2020-10-29 01:49
I believe the default time in code is 1 year, the problem is when/how renews the certificate.
I'd like to close this issue, WDYT? @r0ckarong

**Comment by r0ckarong** [comment] 2020-10-29 10:12
As long as the certs are automatically renewed I don't see a problem. But that's not my call.

@Martin-Weiss Can this be closed?

**Comment by Martin-Weiss** [comment] 2020-11-02 07:05
Once documentation is correct and the renewal for all certs happens automatically- sure - this can be closed..

**Comment by r0ckarong** [comment] 2020-11-02 09:30
> Once documentation is correct and the renewal for all certs happens automatically- sure - this can be closed..

The documentation states that certs have a 1 year validity. I haven't heard any other reports that this isn't true so this case is either a fluke or a bug from what we know. If you have other evidence that this happens more often then please share it so it can be investigated.

From what I understand, the certs are being renewed automatically!?  So what is missing?

cc @jenting

**Comment by Martin-Weiss** [comment] 2020-11-02 09:53
> 
> 
> > Once documentation is correct and the renewal for all certs happens automatically- sure - this can be closed..
> 
> The documentation states that certs have a 1 year validity. I haven't heard any other reports that this isn't true so this case is either a fluke or a bug from what we know. If you have other evidence that this happens more often then please share it so it can be investigated.
> 

Not sure if anyone else than myself ever had a look at the etcd-client-certificate and cilium-secret - but at least in my cluster these two had 2 years.. maybe this got changed in one or the other release.. not sure how to find out when and where this got changed - but if that is in my cluster I assume there might also be other clusters out there, that have some certificates with two years.. and that is the reason why I created this issue to clarify..

> From what I understand, the certs are being renewed automatically!? So what is missing?

I do not know - if all certs are documented and renewed - maybe only the background for the two years might be missing..

> 
> cc @jenting

**Comment by jenting** [comment] 2020-11-11 01:58
I'm sure all the certificates except CA, the validity is 1 year by default.

However, there might a situation that skuba _or_ other component performs the certificate extend to 2 years, but it has to check the skuba code from version to version, and it's a lot of effort on it.

**Comment by r0ckarong** [comment] 2020-11-13 11:32
Closing this. Given the current situation I don't think this is worth investigating further.

**Closed by r0ckarong** 2020-11-13 11:32 UTC
Labels: AdminGuide, Blocked, EngineeringInput, Enhancement
